stages:
  - build
  - test
  - deploy

default:
  image: docker:24.0.5
  services:
    - docker:24.0.5-dind
  tags:
    - docker

variables:
  IMAGE_TAG: registry.td.nchc.org.tw/llm-taskforce/docs/rhap-docs:$CI_COMMIT_REF_SLUG
  PAGES_DIR: public

build:
  stage: build
  script:
    - echo "CI_REGISTRY=$CI_REGISTRY"
    - echo "IMAGE_TAG=$IMAGE_TAG"
    - docker info --format '{{.ServerVersion}}'
    - echo "$CI_REGISTRY_PASSWORD" | docker login registry.td.nchc.org.tw -u $CI_REGISTRY_USER --password-stdin
    - docker build -t $IMAGE_TAG -f rhap/Dockerfile rhap/
    - docker push $IMAGE_TAG
  rules:
    - if: '$CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH'

test:
  stage: test
  image: curlimages/curl:latest
  script:
    - sleep 30
    - curl -f --connect-timeout 5 https://llm-taskforce.pages.td.nchc.org.tw/docs/rhap-docs/ || exit 1
  retry:
    max: 2
    when: script_failure
  needs: ["build"]


pages:
  stage: deploy
  image: node:23.1.0-alpine3.20
  script:
    - cd rhap
    - cp .env.page .env
    - npm install
    - npm run build
    - mv ./build ../public
  artifacts:
    paths:
      - public
  rules:
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH
