variables:
  IMAGE_TAG: $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA
  PAGES_DIR: public

stages:
  - build
  - test
  - deploy


build:
  stage: build
  image:
    name: gcr.io/kaniko-project/executor:v1.9.0
    entrypoint: [""]
  script:
    - /kaniko/executor
      --context "${CI_PROJECT_DIR}"
      --dockerfile "${CI_PROJECT_DIR}/Dockerfile"
      --destination "${IMAGE_TAG}"
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH


test:
  stage: test
  image: docker:24.0.5
  services:
    - name: $IMAGE_TAG
      alias: app
  script:
    - apk add --no-cache curl
    - sleep 20  
    - curl -f http://app:3000 || (docker logs app && exit 1)
    - docker inspect app --format '{{.State.Health.Status}}' | grep -q healthy
  needs: ["build"]


pages:
  stage: deploy
  image: node:23.1.0-alpine3.20
  script:
    - cd rhap
    - cp .env.page .env
    - npm install
    - npm run build
    - mv ./build ../public
  artifacts:
    paths:
      - public
  rules:
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH
