
stages:
  - deploy
deploy-job:
  stage: deploy
  script:
    - ls -la
    - echo "niaho China!" > sample.config.ts
    - scp sample.config.ts ubuntu@103.124.74.43:/home/ubuntu/docusaurus/sample.config.ts
