image: node:23.1.0-alpine3.20

stages:
  - deploy

pages:
  stage: deploy
  script:
    - cd rhap
    - cp .env.page .env
    - npm install
    - npm run build
    - mv ./build ../public
  artifacts:
    paths:
      - public
  rules:
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH
