image: node:23.1.0-alpine3.20

stages:
  - deploy

pages:
  stage: deploy
  script:
  - cd rhap
  - yarn install
  - yarn build
  - mv ./build ../public
  artifacts:
    paths:
    - public
  only:
    - main
