import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 * - create an ordered group of docs
 * - render a sidebar for each doc of that group
 * - provide next/previous navigation
 *
 * The sidebars can be generated from the filesystem, or explicitly defined here.
 *
 * Create as many sidebars as you want.
 */

// const sidebars: SidebarsConfig = {
//   // By default, Docusaurus generates a sidebar from the docs folder structure
//   tutorialSidebar: [{ type: 'autogenerated', dirName: '.' }],
// };

const sidebars: SidebarsConfig = {
  Sidebar: [
    {
      type: 'doc',
      id: 'home',
      label: 'RHAP 大型語言模型高效能 AI 平台',
    },
    {
      type: 'category',
      label: '快速上手',
      collapsed: false, // 停用折疊
      items: [
        '快速上手/簡易安裝',
        '快速上手/服務架設'
      ],
    },
    {
      type: 'category',
      label: '服務介紹',
      collapsed: false, // 停用折疊
      items: [
        'services/All-in-one集合式服務',
        'services/API Server服務',
        'services/輕量化前端服務',
        'services/Lightweight API Portal',
      ],
    },
    {
      type: 'category',
      label: '工具使用說明',
      collapsed: false, // 停用折疊
      items: [
        'tools/AnythingLLM 使用說明',
        'tools/OpenWebUI 使用說明',
        'tools/LiteLLM 使用說明',
        'tools/Lightweight API 使用說明',
      ],
    },
    {
      type: 'category',
      label: '常見問題',
      collapsed: false, // 停用折疊
      items: [
        'faq/technical-issue',
        'faq/OpenAI API 教學',
      ],
    },
  ],
};
export default sidebars;


// 你也可以手動創建一個側邊欄
/*
tutorialSidebar: [
  'intro',
  'hello',
  {
    type: 'category',
    label: 'Tutorial',
    items: ['tutorial-basics/create-a-document'],
  },
],
*/
