import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 * - create an ordered group of docs
 * - render a sidebar for each doc of that group
 * - provide next/previous navigation
 *
 * The sidebars can be generated from the filesystem, or explicitly defined here.
 *
 * Create as many sidebars as you want.
 */

// const sidebars: SidebarsConfig = {
//   // By default, Docusaurus generates a sidebar from the docs folder structure
//   tutorialSidebar: [{ type: 'autogenerated', dirName: '.' }],
// };

const sidebars: SidebarsConfig = {
  Sidebar: [
    {
      type: 'doc',
      id: 'home',
      label: 'RHAP 大型語言模型高效能 AI 平台',
    },
    {
      type: 'doc',
      id: 'quick-start',
      label: '快速上手',
    },
    {
      type: 'category',
      label: '服務介紹',
      items: [
        'services/hydra',
        'services/medusa',
        'services/hummingbird',
        'services/Lightweight',
      ],
    },
    {
      type: 'category',
      label: '工具使用說明',
      items: [
        'tools/AnythingLLM',
        'tools/OpenWebUI',
        'tools/LiteLLM',
        'tools/Lightweight-api',
      ],
    },
    {
      type: 'category',
      label: '常見問題',
      items: [
        'faq/technical-issue',
      ],
    },
  ],
};

export default sidebars;

// 你也可以手動創建一個側邊欄
/*
tutorialSidebar: [
  'intro',
  'hello',
  {
    type: 'category',
    label: 'Tutorial',
    items: ['tutorial-basics/create-a-document'],
  },
],
*/

export default sidebars;
