import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 * - create an ordered group of docs
 * - render a sidebar for each doc of that group
 * - provide next/previous navigation
 *
 * The sidebars can be generated from the filesystem, or explicitly defined here.
 *
 * Create as many sidebars as you want.
 */

// const sidebars: SidebarsConfig = {
//   // By default, Docusaurus generates a sidebar from the docs folder structure
//   tutorialSidebar: [{ type: 'autogenerated', dirName: '.' }],
// };

const sidebars: SidebarsConfig = {
  // 手動定義側邊欄
  tutorialSidebar: [
    {
      type: 'doc',
      id: 'home', // 指向 docs/home.md
      label: 'RHAP 大型語言模型高效能 AI 平台',
    },
    {
      type: 'doc',
      id: 'quick-start', // 指向 docs/quick-start.md
      label: '快速上手',
    },
    {
      type: 'category',
      label: '服務介紹',
      items: [
        'services/hydra', // 指向 docs/services/hydra.md
        'services/medusa', // 指向 docs/services/medusa.md
        'services/hummingbird', // 指向 docs/services/hummingbird.md
        'services/Lightweight', // 指向 docs/services/Lightweight.md
        'services/technical-issue', // 指向 docs/services/technical-issue.md
      ],
    },
    {
      type: 'category',
      label: '工具使用說明',
      items: [
        'tools/AnythingLLM', // 指向 docs/tools/AnythingLLM.md
        'tools/OpenWebUI', // 指向 docs/tools/OpenWebUI.md
        'tools/LiteLLM', // 指向 docs/tools/LiteLLM.md
        'tools/Lightweight-api', // 指向 docs/tools/Lightweight-api.md
      ],
    },
  ],
};

// 你也可以手動創建一個側邊欄
/*
tutorialSidebar: [
  'intro',
  'hello',
  {
    type: 'category',
    label: 'Tutorial',
    items: ['tutorial-basics/create-a-document'],
  },
],
*/

export default sidebars;
